version: 2
multi-ecosystem-groups:
  dependency-updates:
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    cooldown:
      default-days: 2
    groups:
      all-npm-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
    multi-ecosystem-group: "dependency-updates"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    groups:
      all-github-actions-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
    multi-ecosystem-group: "dependency-updates"
