version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 2
    groups:
      npm-minor-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      all-npm-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      all-github-actions-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/wasm"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor-patch-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      all-cargo-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
