version: '3'
services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/myapp
    command: bash -c "wasm-pack build --target web && rm ./pkg/.gitignore"
